#!/usr/bin/expect

#Usage remoteExec <host> <command> <ssh_u> <ssh_p> <stayed_login>

set timeout 10
set host [lindex $argv 0]
set command [lindex $argv 1]
set sshUser [lindex $argv 2]
set pass [lindex $argv 3]
set root [lindex $argv 4]
set stay [lindex $argv 5]

spawn ssh $sshUser@$host

expect "yes/no" { 
	send "yes\r"
	expect "*?assword" { send "[lindex $pass]\r" }
	} "*?assword" { send "[lindex $pass]\r" }

if { $root == 1 } {
	expect "*$*" { send "sudo su\r" }
	expect "*?assword*" { send "[lindex $pass]\r" }
	if { $stay == 0 } {
		expect "*#*" { send "$command\r" }	
		expect "*#*" { send "[lindex exit]\r" }
	}
} else {
	if { $stay == 0 } {
		expect "*$*" { send "$command\r" }
	}		
} 

if { $stay == 0 } {
	expect "*$*" { send "[lindex exit]\r" }
	exit
} else {
	interact
}