#!/usr/bin/expect
#exp_internal 1
#Usage remoteExec <host> <command> <ssh_u> <ssh_p> <stayed_login> <bastion_host>
set timeout 200
set host [lindex $argv 0]
set command [lindex $argv 1]
set sshUser [lindex $argv 2]
set pass [lindex $argv 3]
set root [lindex $argv 4]
set stay [lindex $argv 5]
set bastionHost [lindex $argv 6]




if { $bastionHost == "null" } {
	spawn ssh $sshUser@$host
} else {
	spawn ssh $sshUser@$bastionHost
	expect {
		"yes/no" { send "yes\r";exp_continue } 
		"*?assword" { send "$pass\r" }
		"again" exit
		"*$*" {send "\r"}
	}
	
	#login to target host from bastion host
	expect "*$*" {send "ssh $sshUser@$host\r"}
}

expect {
	"yes/no" { send "yes\r"; exp_continue }
	"*?assword*" { send "$pass\r";exp_continue }
	"again" exit
	"*$*" {send "\r"}
}

if { $root == 1 } {
	expect {
		"*$*" { send "pbrun su -\r"  
			expect {
				"*identity*" { send "sudo su -\r"; exp_continue }
				"*?assword*" { send "$pass\r"; exp_continue }
				"again" exit
				"*#*" {send "\r"}
			}
		}
		"*#*" {send "\r"}
	}

	if { $stay == 0 } {
		expect "*#*" { send "$command\r" } 
		expect "*#*" { send "exit\r" } 
		expect "*$*" { send "exit\r" }
		expect "bulwark" { send "exit\r" }
	} else {
        	interact
	}
} else {
	if { $stay == 0 } {
		expect "*$*" { send "$command\r" }
		expect "*$*" { send "exit\r" }
		expect "bulwark" { send "exit\r" }
	} else {
        	interact
	}		
} 
