#!/usr/bin/expect

#Usage remoteExec <host> <file> <ssh_u> <ssh_p> <bastion>

set timeout 6000
set sshUser [lindex $argv 2]
set pass [lindex $argv 3]
set files [lindex $argv 1]
set host [lindex $argv 0]
set bastion [lindex $argv 4]

spawn scp "$files" $sshUser@$bastion:.
expect "yes/no" {
        send "yes\r"
        expect "*?assword" { send "[lindex $pass]\r" }
        } "*?assword" { send "[lindex $pass]\r" }

expect {
    "ETA" {exp_continue}
    "100%" {}
}
expect eof

spawn ssh $sshUser@$bastion 
expect "yes/no" {
        send "yes\r"
        expect "*?assword" { send "[lindex $pass]\r" }
        } "*?assword" { send "[lindex $pass]\r" }

expect "*$*" { send  "scp $files $sshUser@$host:.\r" }
expect "yes/no" { 
	send "yes\r"
	expect "*?assword" { send "[lindex $pass]\r" }
	} "*?assword" { send "[lindex $pass]\r" }

expect "*$*" { send "ssh $sshUser@$host\r" }
expect "yes/no" {
        send "yes\r"
        expect "*?assword" { send "[lindex $pass]\r" }
        } "*?assword" { send "[lindex $pass]\r" }
expect "*$*" { send "tar -xf $files\r" }
expect "*$*" { send "rm -f $files\r" }
expect "*$*" { send "[lindex exit]\r" }

expect "*$*" { send "rm -f $files\r" }
expect "*$*" { send "[lindex exit]\r" }
