#!/usr/bin/expect

#Usage remoteExec <host> <file> <ssh_u> <ssh_p>

set timeout 10
set sshUser [lindex $argv 2]
set pass [lindex $argv 3]

spawn scp [lindex $argv 1] $sshUser@[lindex $argv 0]:.
expect "*?assword*" { send "$pass\r" }
expect "*$*" { send "[lindex exit]\r" }
