#!/usr/bin/expect

#Usage remoteExec <host> <command>

set timeout 60
set sshUser har.sampathnarayanan
set pass LdapAccessP@\$7
spawn ssh [lindex $sshUser]@[lindex $argv 0]

expect "yes/no" { 
	send "yes\r"
	expect "*?assword" { send "[lindex $pass]\r" }
	} "*?assword" { send "[lindex $pass]\r" }

expect "*$*" { send "sudo su\r" }
expect "*?assword*" { send "[lindex $pass]\r" }
interact
